## ======================================================================
## resources
## ======================================================================

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: gpdb_pr
  type: pull-request
  source:
    repository: greenplum-db/gpdb
    base_branch: "master"
    access_token: ((gpdb-git-access-token))
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpdb7-centos7-build
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-centos7-build

- name: gpdb7-centos7-test
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-centos7-test

- name: libquicklz-centos7
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: gp-internal-artifacts/centos7/libquicklz-(1\.5\.0-.*)-1.el7.x86_64.rpm

- name: libquicklz-devel-centos7
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: gp-internal-artifacts/centos7/libquicklz-devel-(1\.5\.0-.*)-1.el7.x86_64.rpm

- name: clang_toolchain
  type: registry-image
  source:
    repository: gcr.io/data-orca/clang-toolchain

jobs:
- name: compile_and_test_gpdb
  public: true
  max_in_flight: 10
  plan:
  - in_parallel:
    - get: gpdb_pr
      trigger: true
      version: every
    - get: gpdb7-centos7-build
    - get: gpdb7-centos7-test
    - get: libquicklz-installer
      resource: libquicklz-centos7
    - get: libquicklz-devel-installer
      resource: libquicklz-devel-centos7
    - get: clang_toolchain

  - put: gpdb_pr
    params:
      path: gpdb_pr
      status: pending
  - # "do" the remaining steps with these hooks:
    on_failure:
      put: gpdb_pr
      params:
        path: gpdb_pr
        status: failure
    on_success:
      put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
    do:
    - task: init gpdb_src  # Fetch tags and submodules, because the PR resource doesn't.
      image: gpdb7-centos7-build
      config:
        platform: linux
        run:
          path: bash
          args:
          - -c
          - |
            git clone gpdb_pr gpdb_src &&
            cd gpdb_src &&
            git fetch https://github.com/greenplum-db/gpdb.git --tags &&
            git submodule update --init --recursive
        inputs: [{ name: gpdb_pr }]
        outputs: [{ name: gpdb_src }]
    - task: check_format
      image: clang_toolchain
      file: gpdb_src/concourse/tasks/check_format.yml
    - task: compile_gpdb_centos7
      file: gpdb_pr/concourse/tasks/compile_gpdb.yml
      image: gpdb7-centos7-build
      params:
        CONFIGURE_FLAGS: ((configure_flags_with_extensions))
        TARGET_OS: centos
        TARGET_OS_VERSION: 7
        BLD_TARGETS: "clients loaders"
      timeout: 30m


    - in_parallel:
      - task: icw_planner_centos7
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-centos7-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: ((configure_flags))
        timeout: 3h

      - task: icw_gporca_centos7
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-centos7-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: ((configure_flags))
        timeout: 5h
