## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: pull_request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: gpdb_pr
    type: pull_request
    source:
      repo: greenplum-db/gpdb
      access_token: {{gpdb-git-access-token}}
      ignore_paths:
      - gpdb-doc/*
      - README*

  - name: ubuntu-gpdb-dev-16
    type: docker-image
    source:
      repository: pivotaldata/ubuntu-gpdb-dev
      tag: '16.04'

jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 10
    plan:
    - aggregate:
      - get: gpdb_pr
        trigger: true
        version: every
      - get: ubuntu-gpdb-dev-16

    - put: gpdb_pr
      params:
        path: gpdb_pr
        status: pending

    - task: compile_gpdb_ubuntu16
      file: gpdb_pr/concourse/tasks/compile_gpdb_open_source_ubuntu.yml
      image: ubuntu-gpdb-dev-16
      input_mapping:
        gpdb_src: gpdb_pr
      on_failure: &pr_failure
        put: gpdb_pr
        params:
          path: gpdb_pr
          status: failure
      timeout: 30m
      params:
        BINTRAY_REMOTE: {{bintray_remote}}
        BINTRAY_REMOTE_URL: {{bintray_remote_url}}

    - aggregate:
      - task: icw_gporca_ubuntu16
        image: ubuntu-gpdb-dev-16
        file: gpdb_pr/concourse/tasks/test_with_orca_conan.yml
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: compiled_bits_ubuntu16
        params:
          TEST_SUITE: "icw"
        timeout: 3h
        on_failure: *pr_failure

      - task: icw_planner_ubuntu16
        image: ubuntu-gpdb-dev-16
        file: gpdb_pr/concourse/tasks/test_with_planner_conan.yml
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: compiled_bits_ubuntu16
        params:
          TEST_SUITE: "icw"
        timeout: 3h
        on_failure: *pr_failure

    - put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
