Vagrant.configure("2") do |config|
  config.vm.box = "cloudberrydb/dev10-centos7"
  config.vm.box_version = "20221011"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 8
    vb.memory = "14336"
  end

  config.vm.synced_folder "../../.", "/home/gpadmin/workspace/cbdb", owner: "gpadmin", group: "gpadmin", :extra => "dmode=555,fmode=555"
  if ENV['CBDB_TEST_REPO_PATH'] != nil then
    config.vm.synced_folder ENV['CBDB_TEST_REPO_PATH'], "/home/gpadmin/workspace/cbdb_testrepo", owner: "gpadmin", group: "root", :extra => "dmode=755,fmode=755"
  end
  if ENV['CBDB_TEST_TPCH_PATH'] != nil then 
    config.vm.synced_folder ENV['CBDB_TEST_TPCH_PATH'], "/home/gpadmin/workspace/tpch", owner: "gpadmin", group: "root", :extra => "dmode=755,fmode=755"
  end
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    user=gpadmin
    su - $user -c "echo "source ~/workspace/cbdb/deploy/cbdb_env.sh" >> /home/$user/.bashrc"
    chmod u+x /home/$user/workspace/cbdb/deploy/cbdb_deploy.sh &&
    su - $user -c "/home/$user/workspace/cbdb/deploy/cbdb_deploy.sh build"
  SHELL
end
