subdir=src/backend/utils/sort
top_builddir=../../../../..
include $(top_builddir)/src/Makefile.global

TARGETS=string_wrapper

include $(top_srcdir)/src/backend/mock.mk

string_wrapper.t: $(MOCK_DIR)/backend/access/hash/hash_mock.o \
	$(MOCK_DIR)/backend/utils/fmgr/fmgr_mock.o \
