#!/bin/sh
#
# A hook script to prepare the commit log message. Called by "git commit" with
# the name of the file that has the commit message, followed by the
# description of the commit message's source.  The hook's purpose is to edit
# the commit message file.  If the hook fails with a non-zero status, the
# commit is aborted.
#

cat ./src/tools/hooks/.gitmessage > $1
