#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/resscheduler
#
# IDENTIFICATION
#    src/backend/utils/resscheduler/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/resscheduler
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = resqueue.o resscheduler.o memquota.o

include $(top_srcdir)/src/backend/common.mk