#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/fmgr
#
# IDENTIFICATION
#    src/backend/utils/fmgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/etcd_lib
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	etcd.o

include $(top_srcdir)/src/backend/common.mk
