
BLD_TOP := ../../../../..
include $(BLD_TOP)/make/gpo.mk

INCDIRS = -I $(BLD_TOP)/server/include -I $(BLD_TOP)/libnaucrates/include -I $(LIBGPOS)/include -I $(BLD_TOP)/libgpdbcost/include -I $(BLD_TOP)/libgpopt/include

all: objs
