CPP = g++
CFLAGS = -g3 -std=c++98 -fPIC -fprofile-arcs -ftest-coverage -DDEBUGS3 -DAWSTEST
INCLUDES = -Isrc -Ilib -I/usr/include/libxml2
LDFLAGS = -lpthread -lcrypto -lcurl -lxml2 -lgcov

testcources = src/gps3conf_test.cpp src/utils_test.cpp src/S3Downloader_test.cpp src/S3Common_test.cpp src/S3ExtWrapper_test.cpp src/S3Log_test.cpp

testapp = s3test
testobjs = $(testcources:.cpp=.o)

GTEST_DIR = gtest

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

all: test

$(testobjs) gtest-all.o gtest_main.o: INCLUDES += -I$(GTEST_DIR)/include -I$(GTEST_DIR)/

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized. This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) $(INCLUDES) $(CXXFLAGS) -c $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) $(INCLUDES) $(CXXFLAGS) -c $(GTEST_DIR)/src/gtest_main.cc

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

%.o: %.cpp
	$(CPP) $(CFLAGS) $(INCLUDES) -c $< -o $@

buildtest: gtest_main.a $(testobjs)
	$(CPP) $(CPPFLAGS) $(CXXFLAGS) $^ -o $(testapp) $(LDFLAGS)

test: buildtest
	@./$(testapp) || echo "done"

coverage: test
	@gcov -r $(testcources) | grep -v test.cpp | grep -A 2 "src/.*.cpp"

clean:
	rm -f $(testapp) src/*.o src/*.a lib/*.o *.o *.a
	rm -f *.gcov src/*.gcov src/*.gcda src/*.gcno

distclean: clean
	rm -f tags cscope.*

tags:
	etags src/*.cpp src/*.h

lint:
	cppcheck -v --enable=warning src/*.cpp src/*.h

style:
	astyle -s4 src/*.cpp src/*.h

format:
	clang-format -style="{BasedOnStyle: Google, IndentWidth: 4}" -i src/*.cpp src/*.h

.PHONY: test coverage clean distclean lint style format
