# Options
DEBUG_S3 = y
DEBUG_S3_CURL = n
AWS_TEST = y
FAKE_TEST = y
BIG_FILE_TEST = n

# Flags
CPP = g++
INCLUDES = -Isrc -Ilib -I/usr/include/libxml2
LDFLAGS = -lpthread -lcrypto -lcurl -lxml2 -lgcov -lz
CFLAGS = -O2 -g3 -std=c++98 -fPIC -fprofile-arcs -ftest-coverage

ifeq ($(DEBUG_S3),y)
	CPPFLAGS += -DDEBUG_S3
endif

ifeq ($(DEBUG_S3_CURL),y)
	CPPFLAGS += -DDEBUG_S3_CURL
endif

ifeq ($(AWS_TEST),y)
	CPPFLAGS += -DAWS_TEST
endif

ifeq ($(FAKE_TEST),y)
	CPPFLAGS += -DFAKE_TEST
endif

ifeq ($(BIG_FILE_TEST),y)
	CPPFLAGS += -DBIG_FILE_TEST
endif

all: test

# Google TEST
TEST_SRC_FILES = src/s3conf_test.cpp src/s3utils_test.cpp src/s3downloader_test.cpp src/s3common_test.cpp src/s3wrapper_test.cpp src/s3log_test.cpp
TEST_OBJS = $(TEST_SRC_FILES:.cpp=.o)
TEST_APP = s3test

DEP_FILES := $(patsubst %.cpp,%.d,$(TEST_SRC_FILES))
-include $(DEP_FILES)

GTEST_DIR = ../gtest
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

$(TEST_OBJS) gtest-all.o gtest_main.o: INCLUDES += -I$(GTEST_DIR)/include -I$(GTEST_DIR)/

gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -c $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -c $(GTEST_DIR)/src/gtest_main.cc

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

%.o: %.cpp
	$(CPP) $(CPPFLAGS) $(INCLUDES) -MMD -MP -c $< -o $@

$(TEST_APP): gtest_main.a $(TEST_OBJS)
	$(CPP) $^ -o $(TEST_APP) $(LDFLAGS)

buildtest: $(TEST_APP)

test: $(TEST_APP)
	-@./$(TEST_APP)

coverage: test
	@gcov -r $(TEST_SRC_FILES) | grep -v test.cpp | grep -A 2 "src/.*.cpp"

clean:
	rm -f *.gcov src/*.gcov src/*.gcda src/*.gcno
	rm -f $(TEST_APP) *.so src/*.o src/*.d lib/*.o lib/*.d *.o *.a

distclean: clean
	rm -f tags cscope.*

tags:
	ctags --c++-kinds=+p --fields=+iaS --extra=+q src/*.cpp src/*.h
	cscope -bq src/*.cpp src/*.h

lint:
	cppcheck -v --enable=warning src/*.cpp src/*.h

format:
	clang-format -style="{BasedOnStyle: Google, IndentWidth: 4}" -i src/*.cpp src/*.h

.PHONY: buildtest test coverage clean distclean tags lint format
