#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/common
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/access/common/Makefile,v 1.25 2008/02/19 11:49:12 petere Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/access/common
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = bufmask.o memtuple.o heaptuple.o indextuple.o printtup.o reloptions.o reloptions_gp.o scankey.o tupdesc.o

include $(top_srcdir)/src/backend/common.mk
