#
# Makefile for optimizer
#
# src/backend/gporca/libgpos/src/io/Makefile
#

subdir = src/backend/gporca/libgpos/src/io
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS        = CFileDescriptor.o \
              CFileReader.o \
              CFileWriter.o \
              COstream.o \
              COstreamBasic.o \
              COstreamFile.o \
              COstreamString.o \
              ioutils.o

include $(top_srcdir)/src/backend/common.mk

