#
# Makefile for optimizer
#
# src/backend/gporca/libgpopt/src/engine/Makefile
#

subdir = src/backend/gporca/libgpopt/src/engine
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS        = CEngine.o \
              CEnumeratorConfig.o \
              CPartialPlan.o \
              CStatisticsConfig.o

include $(top_srcdir)/src/backend/common.mk

