#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for gpopt
#
#-------------------------------------------------------------------------

subdir = src/backend/gpopt/config
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = CConfigParamMapping.o

include $(top_srcdir)/src/backend/common.mk
