DROP TABLE IF EXISTS test_co_checksum_01;
DROP TABLE IF EXISTS test_co_checksum_02;
DROP TABLE IF EXISTS test_co_checksum_03;
DROP TABLE IF EXISTS test_co_checksum_04;
DROP TABLE IF EXISTS test_co_checksum_05;
DROP TABLE IF EXISTS test_co_checksum_06;
DROP TABLE IF EXISTS test_co_checksum_07;
DROP TABLE IF EXISTS test_co_checksum_08;
DROP TABLE IF EXISTS test_co_checksum_09;
DROP TABLE IF EXISTS test_co_checksum_10;
CREATE TABLE test_co_checksum_01 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_02 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_03 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_04 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_05 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_06 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_07 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_08 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_09 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
CREATE TABLE test_co_checksum_10 (a int, b int, c int, d int, e int) with (appendonly=true, orientation=column);
