p4 edit ./test_PT_OOM.py
p4 edit ./test_PT_DropDB.py
p4 edit ./test_PT_CrashRecovery.py
p4 edit ./sqls/InitialSetup.py
p4 edit ./sqls/join_query/JoinQuery.py
p4 edit ./sqls/partition_tables/generate_partition_sqls.py
p4 edit ./sqls/partition_tables/partitionTables.py
p4 edit ./sqls/generate_sqls.py
p4 edit ./test_PT_RebuildPT.py
p4 edit ./test_PT_gprecoverseg.py
p4 edit ./fault/fault.py
p4 edit ./PTRebuild/persistent_rebuild_scenario.py
