SELECT CURRENT_TIMESTAMP;

create table subt_for_ctas_ao(i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with (appendonly=true) distributed randomly;
Insert into subt_for_ctas_ao values(generate_series(1,5),'table used for ctas','s','subtransaction table','12-11-2012',3,'2012-10-09 10:23:54', '2011-08-19 10:23:54+02');
-- Values to be inserted in the transactions below are in this table. Not using
-- directly VALUES clause or generate_series() because the reader gang where we
-- intend to inject fault need to happen on the segments. The VALUES clause or
-- generate_series() usage doesn't guarantee such a plan.
create temp table subtransaction_temp (like subt_for_ctas_ao);
Insert into subtransaction_temp values(generate_series(1,4),'create table with subtransactions','s','subtransaction table','12-11-2012',3,'2012-10-09 10:23:54', '2011-08-19 10:23:54+02');
BEGIN;
Savepoint sp1;
Create table subt_tab_distby_ao1 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Savepoint sp2;
Create table subt_tab_distby_ao2 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao1 select * from subtransaction_temp;
Savepoint sp3;
Create table subt_tab_distby_ao3 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao2 select * from subtransaction_temp;
Savepoint sp4;
Create table subt_tab_distby_ao4 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao3 select * from subtransaction_temp;
Savepoint sp5;
Create table subt_tab_distby_ao5 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao4 select * from subtransaction_temp;
Savepoint sp6;
Create table subt_tab_distby_ao6 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao5 select * from subtransaction_temp;
Savepoint sp7;
Create table subt_tab_distby_ao7 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao6 select * from subtransaction_temp;
Savepoint sp8;
Create table subt_tab_distby_ao8 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao7 select * from subtransaction_temp;
Savepoint sp9;
Create table subt_tab_distby_ao9 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao8 select * from subtransaction_temp;
Savepoint sp10;
Create table subt_tab_distby_ao10 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao9 select * from subtransaction_temp;
Savepoint sp11;
Create table subt_tab_distby_ao11 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao10 select * from subtransaction_temp;
Savepoint sp12;
Create table subt_tab_distby_ao12 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao11 select * from subtransaction_temp;
Savepoint sp13;
Create table subt_tab_distby_ao13 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao12 select * from subtransaction_temp;
Savepoint sp14;
Create table subt_tab_distby_ao14 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao13 select * from subtransaction_temp;
Savepoint sp15;
Create table subt_tab_distby_ao15 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao14 select * from subtransaction_temp;
Savepoint sp16;
Create table subt_tab_distby_ao16 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao15 select * from subtransaction_temp;
Savepoint sp17;
Create table subt_tab_distby_ao17 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao16 select * from subtransaction_temp;
Savepoint sp18;
Create table subt_tab_distby_ao18 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao17 select * from subtransaction_temp;
Savepoint sp19;
Create table subt_tab_distby_ao19 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao18 select * from subtransaction_temp;
Savepoint sp20;
Create table subt_tab_distby_ao20 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao19 select * from subtransaction_temp;
Savepoint sp21;
Create table subt_tab_distby_ao21 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao20 select * from subtransaction_temp;
Savepoint sp22;
Create table subt_tab_distby_ao22 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao21 select * from subtransaction_temp;
Savepoint sp23;
Create table subt_tab_distby_ao23 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao22 select * from subtransaction_temp;
Savepoint sp24;
Create table subt_tab_distby_ao24 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao23 select * from subtransaction_temp;
Savepoint sp25;
Create table subt_tab_distby_ao25 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao24 select * from subtransaction_temp;
Savepoint sp26;
Create table subt_tab_distby_ao26 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao25 select * from subtransaction_temp;
Savepoint sp27;
Create table subt_tab_distby_ao27 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao26 select * from subtransaction_temp;
Savepoint sp28;
Create table subt_tab_distby_ao28 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao27 select * from subtransaction_temp;
Savepoint sp29;
Create table subt_tab_distby_ao29 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao28 select * from subtransaction_temp;
Savepoint sp30;
Create table subt_tab_distby_ao30 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao29 select * from subtransaction_temp;
Savepoint sp31;
Create table subt_tab_distby_ao31 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao30 select * from subtransaction_temp;
Savepoint sp32;
Create table subt_tab_distby_ao32 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao31 select * from subtransaction_temp;
Savepoint sp33;
Create table subt_tab_distby_ao33 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao32 select * from subtransaction_temp;
Savepoint sp34;
Create table subt_tab_distby_ao34 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao33 select * from subtransaction_temp;
Savepoint sp35;
Create table subt_tab_distby_ao35 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao34 select * from subtransaction_temp;
Savepoint sp36;
Create table subt_tab_distby_ao36 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao35 select * from subtransaction_temp;
Savepoint sp37;
Create table subt_tab_distby_ao37 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao36 select * from subtransaction_temp;
Savepoint sp38;
Create table subt_tab_distby_ao38 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao37 select * from subtransaction_temp;
Savepoint sp39;
Create table subt_tab_distby_ao39 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao38 select * from subtransaction_temp;
Savepoint sp40;
Create table subt_tab_distby_ao40 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao39 select * from subtransaction_temp;
Savepoint sp41;
Create table subt_tab_distby_ao41 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao40 select * from subtransaction_temp;
Release Savepoint sp41;
Savepoint sp42;
Create table subt_tab_distby_ao42 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao41 select * from subtransaction_temp;
Release Savepoint sp42;
Savepoint sp43;
Create table subt_tab_distby_ao43 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao42 select * from subtransaction_temp;
Release Savepoint sp43;
Savepoint sp44;
Create table subt_tab_distby_ao44 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao43 select * from subtransaction_temp;
Release Savepoint sp44;
Savepoint sp45;
Create table subt_tab_distby_ao45 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao44 select * from subtransaction_temp;
Release Savepoint sp45;
Savepoint sp46;
Create table subt_tab_distby_ao46 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao45 select * from subtransaction_temp;
Release Savepoint sp46;
Savepoint sp47;
Create table subt_tab_distby_ao47 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao46 select * from subtransaction_temp;
Release Savepoint sp47;
Savepoint sp48;
Create table subt_tab_distby_ao48 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao47 select * from subtransaction_temp;
Release Savepoint sp48;
Savepoint sp49;
Create table subt_tab_distby_ao49 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao48 select * from subtransaction_temp;
Release Savepoint sp49;
Savepoint sp50;
Create table subt_tab_distby_ao50 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao49 select * from subtransaction_temp;
Release Savepoint sp50;
Savepoint sp51;
Create table subt_tab_distby_ao51 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao50 select * from subtransaction_temp;
Release Savepoint sp51;
Savepoint sp52;
Create table subt_tab_distby_ao52 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao51 select * from subtransaction_temp;
Release Savepoint sp52;
Savepoint sp53;
Create table subt_tab_distby_ao53 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao52 select * from subtransaction_temp;
Release Savepoint sp53;
Savepoint sp54;
Create table subt_tab_distby_ao54 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao53 select * from subtransaction_temp;
Release Savepoint sp54;
Savepoint sp55;
Create table subt_tab_distby_ao55 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao54 select * from subtransaction_temp;
Release Savepoint sp55;
Savepoint sp56;
Create table subt_tab_distby_ao56 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao55 select * from subtransaction_temp;
Release Savepoint sp56;
Savepoint sp57;
Create table subt_tab_distby_ao57 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao56 select * from subtransaction_temp;
Release Savepoint sp57;
Savepoint sp58;
Create table subt_tab_distby_ao58 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao57 select * from subtransaction_temp;
Release Savepoint sp58;
Savepoint sp59;
Create table subt_tab_distby_ao59 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao58 select * from subtransaction_temp;
Release Savepoint sp59;
Savepoint sp60;
Create table subt_tab_distby_ao60 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao59 select * from subtransaction_temp;
Release Savepoint sp60;
Savepoint sp61;
Create table subt_tab_distby_ao61 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao60 select * from subtransaction_temp;
Release Savepoint sp61;
Savepoint sp62;
Create table subt_tab_distby_ao62 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao61 select * from subtransaction_temp;
Release Savepoint sp62;
Savepoint sp63;
Create table subt_tab_distby_ao63 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao62 select * from subtransaction_temp;
Release Savepoint sp63;
Savepoint sp64;
Create table subt_tab_distby_ao64 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao63 select * from subtransaction_temp;
Release Savepoint sp64;
Savepoint sp65;
Create table subt_tab_distby_ao65 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao64 select * from subtransaction_temp;
Release Savepoint sp65;
Savepoint sp66;
Create table subt_tab_distby_ao66 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao65 select * from subtransaction_temp;
Release Savepoint sp66;
Savepoint sp67;
Create table subt_tab_distby_ao67 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao66 select * from subtransaction_temp;
Release Savepoint sp67;
Savepoint sp68;
Create table subt_tab_distby_ao68 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao67 select * from subtransaction_temp;
Release Savepoint sp68;
Savepoint sp69;
Create table subt_tab_distby_ao69 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao68 select * from subtransaction_temp;
Release Savepoint sp69;
Savepoint sp70;
Create table subt_tab_distby_ao70 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao69 select * from subtransaction_temp;
Release Savepoint sp70;
Savepoint sp71;
Create table subt_tab_distby_ao71 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao70 select * from subtransaction_temp;
Release Savepoint sp71;
Savepoint sp72;
Create table subt_tab_distby_ao72 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao71 select * from subtransaction_temp;
Release Savepoint sp72;
Savepoint sp73;
Create table subt_tab_distby_ao73 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao72 select * from subtransaction_temp;
Release Savepoint sp73;
Savepoint sp74;
Create table subt_tab_distby_ao74 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao73 select * from subtransaction_temp;
Release Savepoint sp74;
Savepoint sp75;
Create table subt_tab_distby_ao75 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao74 select * from subtransaction_temp;
Release Savepoint sp75;
Savepoint sp76;
Create table subt_tab_distby_ao76 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao75 select * from subtransaction_temp;
Release Savepoint sp76;
Savepoint sp77;
Create table subt_tab_distby_ao77 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao76 select * from subtransaction_temp;
Release Savepoint sp77;
Savepoint sp78;
Create table subt_tab_distby_ao78 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao77 select * from subtransaction_temp;
Release Savepoint sp78;
Savepoint sp79;
Create table subt_tab_distby_ao79 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao78 select * from subtransaction_temp;
Release Savepoint sp79;
Savepoint sp80;
Create table subt_tab_distby_ao80 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao79 select * from subtransaction_temp;
Release Savepoint sp80;
Savepoint sp81;
Create table subt_tab_distby_ao81 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao81 select * from subtransaction_temp;
Rollback to sp81;
Savepoint sp82;
Create table subt_tab_distby_ao82 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao82 select * from subtransaction_temp;
Rollback to sp82;
Savepoint sp83;
Create table subt_tab_distby_ao83 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao83 select * from subtransaction_temp;
Rollback to sp83;
Savepoint sp84;
Create table subt_tab_distby_ao84 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao84 select * from subtransaction_temp;
Rollback to sp84;
Savepoint sp85;
Create table subt_tab_distby_ao85 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao85 select * from subtransaction_temp;
Rollback to sp85;
Savepoint sp86;
Create table subt_tab_distby_ao86 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao86 select * from subtransaction_temp;
Rollback to sp86;
Savepoint sp87;
Create table subt_tab_distby_ao87 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao87 select * from subtransaction_temp;
Rollback to sp87;
Savepoint sp88;
Create table subt_tab_distby_ao88 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao88 select * from subtransaction_temp;
Rollback to sp88;
Savepoint sp89;
Create table subt_tab_distby_ao89 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao89 select * from subtransaction_temp;
Rollback to sp89;
Savepoint sp90;
Create table subt_tab_distby_ao90 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao90 select * from subtransaction_temp;
Rollback to sp90;
Savepoint sp91;
Create table subt_tab_distby_ao91 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao91 select * from subtransaction_temp;
Rollback to sp91;
Savepoint sp92;
Create table subt_tab_distby_ao92 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao92 select * from subtransaction_temp;
Rollback to sp92;
Savepoint sp93;
Create table subt_tab_distby_ao93 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao93 select * from subtransaction_temp;
Rollback to sp93;
Savepoint sp94;
Create table subt_tab_distby_ao94 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao94 select * from subtransaction_temp;
Rollback to sp94;
Savepoint sp95;
Create table subt_tab_distby_ao95 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao95 select * from subtransaction_temp;
Rollback to sp95;
Savepoint sp96;
Create table subt_tab_distby_ao96 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao96 select * from subtransaction_temp;
Rollback to sp96;
Savepoint sp97;
Create table subt_tab_distby_ao97 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao97 select * from subtransaction_temp;
Rollback to sp97;
Savepoint sp98;
Create table subt_tab_distby_ao98 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao98 select * from subtransaction_temp;
Rollback to sp98;
Savepoint sp99;
Create table subt_tab_distby_ao99 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao99 select * from subtransaction_temp;
Rollback to sp99;
Savepoint sp100;
Create table subt_tab_distby_ao100 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao100 select * from subtransaction_temp;
Rollback to sp100;
Savepoint sp101;
Create table subt_tab_distby_ao101 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Release Savepoint sp101;
Savepoint sp102;
Create table subt_tab_distby_ao101 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao101 select * from subtransaction_temp;
Rollback to sp102;
Savepoint sp96;
Create table subt_tab_distby_ao96 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Release Savepoint sp96;
Savepoint sp97;
Create table subt_tab_distby_ao96 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao96 select * from subtransaction_temp;
Rollback to sp97;
Savepoint sp102;
Create table subt_tab_distby_ao102 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao101 select * from subtransaction_temp;
Savepoint sp103;
Create table subt_tab_distby_ao103 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao102 select * from subtransaction_temp;
Savepoint sp104;
Create table subt_tab_distby_ao104 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao103 select * from subtransaction_temp;
Savepoint sp105;
Create table subt_tab_distby_ao105 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao104 select * from subtransaction_temp;
Savepoint sp106;
Create table subt_tab_distby_ao106 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao105 select * from subtransaction_temp;
Savepoint sp107;
Create table subt_tab_distby_ao107 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao106 select * from subtransaction_temp;
Savepoint sp108;
Create table subt_tab_distby_ao108 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao107 select * from subtransaction_temp;
Savepoint sp109;
Create table subt_tab_distby_ao109 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao108 select * from subtransaction_temp;
Savepoint sp110;
Create table subt_tab_distby_ao110 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao109 select * from subtransaction_temp;
Savepoint sp111;
Create table subt_tab_distby_ao111 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao110 select * from subtransaction_temp;
Savepoint sp112;
Create table subt_tab_distby_ao112 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao111 select * from subtransaction_temp;
Savepoint sp113;
Create table subt_tab_distby_ao113 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao112 select * from subtransaction_temp;
Savepoint sp114;
Create table subt_tab_distby_ao114 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao113 select * from subtransaction_temp;
Savepoint sp115;
Create table subt_tab_distby_ao115 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao114 select * from subtransaction_temp;
Savepoint sp116;
Create table subt_tab_distby_ao116 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao115 select * from subtransaction_temp;
Savepoint sp117;
Create table subt_tab_distby_ao117 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao116 select * from subtransaction_temp;
Savepoint sp118;
Create table subt_tab_distby_ao118 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao117 select * from subtransaction_temp;
Savepoint sp119;
Create table subt_tab_distby_ao119 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao118 select * from subtransaction_temp;
Savepoint sp120;
Create table subt_tab_distby_ao120 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao119 select * from subtransaction_temp;
Savepoint sp121;
Create table subt_tab_distby_ao121 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao120 select * from subtransaction_temp;
Savepoint sp122;
Create table subt_tab_distby_ao122 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao121 select * from subtransaction_temp;
Savepoint sp123;
Create table subt_tab_distby_ao123 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao122 select * from subtransaction_temp;
Savepoint sp124;
Create table subt_tab_distby_ao124 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao123 select * from subtransaction_temp;
Savepoint sp125;
Create table subt_tab_distby_ao125 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao124 select * from subtransaction_temp;
Savepoint sp126;
Create table subt_tab_distby_ao126 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao125 select * from subtransaction_temp;
Savepoint sp127;
Create table subt_tab_distby_ao127 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao126 select * from subtransaction_temp;
Savepoint sp128;
Create table subt_tab_distby_ao128 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao127 select * from subtransaction_temp;
Savepoint sp129;
Create table subt_tab_distby_ao129 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao128 select * from subtransaction_temp;
Savepoint sp130;
Create table subt_tab_distby_ao130 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao129 select * from subtransaction_temp;
Savepoint sp131;
Create table subt_tab_distby_ao131 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao130 select * from subtransaction_temp;
Savepoint sp132;
Create table subt_tab_distby_ao132 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao131 select * from subtransaction_temp;
Savepoint sp133;
Create table subt_tab_distby_ao133 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao132 select * from subtransaction_temp;
Savepoint sp134;
Create table subt_tab_distby_ao134 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao133 select * from subtransaction_temp;
Savepoint sp135;
Create table subt_tab_distby_ao135 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao134 select * from subtransaction_temp;
Savepoint sp136;
Create table subt_tab_distby_ao136 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao135 select * from subtransaction_temp;
Savepoint sp137;
Create table subt_tab_distby_ao137 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao136 select * from subtransaction_temp;
Savepoint sp138;
Create table subt_tab_distby_ao138 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao137 select * from subtransaction_temp;
Savepoint sp139;
Create table subt_tab_distby_ao139 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao138 select * from subtransaction_temp;
Savepoint sp140;
Create table subt_tab_distby_ao140 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao139 select * from subtransaction_temp;
Savepoint sp141;
Create table subt_tab_distby_ao141 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao140 select * from subtransaction_temp;
Savepoint sp142;
Create table subt_tab_distby_ao142 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao141 select * from subtransaction_temp;
Savepoint sp143;
Create table subt_tab_distby_ao143 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao142 select * from subtransaction_temp;
Savepoint sp144;
Create table subt_tab_distby_ao144 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao143 select * from subtransaction_temp;
Savepoint sp145;
Create table subt_tab_distby_ao145 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao144 select * from subtransaction_temp;
Savepoint sp146;
Create table subt_tab_distby_ao146 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao145 select * from subtransaction_temp;
Savepoint sp147;
Create table subt_tab_distby_ao147 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao146 select * from subtransaction_temp;
Savepoint sp148;
Create table subt_tab_distby_ao148 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao147 select * from subtransaction_temp;
Savepoint sp149;
Create table subt_tab_distby_ao149 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao148 select * from subtransaction_temp;
Savepoint sp150;
Create table subt_tab_distby_ao150 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao149 select * from subtransaction_temp;
Rollback to sp142;
Savepoint sp142;
Create table subt_tab_distby_ao142 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao141 select * from subtransaction_temp;
Release Savepoint sp142;
Savepoint sp143;
Create table subt_tab_distby_ao143 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao142 select * from subtransaction_temp;
Release Savepoint sp143;
Savepoint sp144;
Create table subt_tab_distby_ao144 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao143 select * from subtransaction_temp;
Release Savepoint sp144;
Savepoint sp145;
Create table subt_tab_distby_ao145 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao144 select * from subtransaction_temp;
Release Savepoint sp145;
Savepoint sp146;
Create table subt_tab_distby_ao146 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao145 select * from subtransaction_temp;
Release Savepoint sp146;
Savepoint sp147;
Create table subt_tab_distby_ao147 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao146 select * from subtransaction_temp;
Release Savepoint sp147;
Savepoint sp148;
Create table subt_tab_distby_ao148 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao147 select * from subtransaction_temp;
Release Savepoint sp148;
Savepoint sp149;
Create table subt_tab_distby_ao149 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao148 select * from subtransaction_temp;
Release Savepoint sp149;
Savepoint sp150;
Create table subt_tab_distby_ao150 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao149 select * from subtransaction_temp;
Release Savepoint sp150;
Savepoint sp151;
Create table subt_tab_distby_ao151 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao150 select * from subtransaction_temp;
Release Savepoint sp151;
Savepoint sp152;
Create table subt_tab_distby_ao152 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao151 select * from subtransaction_temp;
Release Savepoint sp152;
Savepoint sp153;
Create table subt_tab_distby_ao153 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao152 select * from subtransaction_temp;
Release Savepoint sp153;
Savepoint sp154;
Create table subt_tab_distby_ao154 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao153 select * from subtransaction_temp;
Release Savepoint sp154;
Savepoint sp155;
Create table subt_tab_distby_ao155 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao154 select * from subtransaction_temp;
Release Savepoint sp155;
Savepoint sp156;
Create table subt_tab_distby_ao156 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao155 select * from subtransaction_temp;
Release Savepoint sp156;
Savepoint sp157;
Create table subt_tab_distby_ao157 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao156 select * from subtransaction_temp;
Release Savepoint sp157;
Savepoint sp158;
Create table subt_tab_distby_ao158 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao157 select * from subtransaction_temp;
Release Savepoint sp158;
Savepoint sp159;
Create table subt_tab_distby_ao159 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao158 select * from subtransaction_temp;
Release Savepoint sp159;
Savepoint sp160;
Create table subt_tab_distby_ao160 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao159 select * from subtransaction_temp;
Release Savepoint sp160;
Savepoint sp161;
Create table subt_tab_distby_ao161 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao160 select * from subtransaction_temp;
Release Savepoint sp161;
Savepoint sp162;
Create table subt_tab_distby_ao162 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao161 select * from subtransaction_temp;
Release Savepoint sp162;
Savepoint sp163;
Create table subt_tab_distby_ao163 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao162 select * from subtransaction_temp;
Release Savepoint sp163;
Savepoint sp164;
Create table subt_tab_distby_ao164 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao163 select * from subtransaction_temp;
Release Savepoint sp164;
Savepoint sp165;
Create table subt_tab_distby_ao165 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao164 select * from subtransaction_temp;
Release Savepoint sp165;
Savepoint sp166;
Create table subt_tab_distby_ao166 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao165 select * from subtransaction_temp;
Release Savepoint sp166;
Savepoint sp167;
Create table subt_tab_distby_ao167 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao166 select * from subtransaction_temp;
Release Savepoint sp167;
Savepoint sp168;
Create table subt_tab_distby_ao168 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao167 select * from subtransaction_temp;
Release Savepoint sp168;
Savepoint sp169;
Create table subt_tab_distby_ao169 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao168 select * from subtransaction_temp;
Release Savepoint sp169;
Savepoint sp170;
Create table subt_tab_distby_ao170 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao169 select * from subtransaction_temp;
Release Savepoint sp170;
Savepoint sp171;
Create table subt_tab_distby_ao171 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao170 select * from subtransaction_temp;
Release Savepoint sp171;
Savepoint sp172;
Create table subt_tab_distby_ao172 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao171 select * from subtransaction_temp;
Release Savepoint sp172;
Savepoint sp173;
Create table subt_tab_distby_ao173 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao172 select * from subtransaction_temp;
Release Savepoint sp173;
Savepoint sp174;
Create table subt_tab_distby_ao174 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao173 select * from subtransaction_temp;
Release Savepoint sp174;
Savepoint sp175;
Create table subt_tab_distby_ao175 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao174 select * from subtransaction_temp;
Release Savepoint sp175;
Savepoint sp176;
Create table subt_tab_distby_ao176 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao175 select * from subtransaction_temp;
Release Savepoint sp176;
Savepoint sp177;
Create table subt_tab_distby_ao177 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao176 select * from subtransaction_temp;
Release Savepoint sp177;
Savepoint sp178;
Create table subt_tab_distby_ao178 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao177 select * from subtransaction_temp;
Release Savepoint sp178;
Savepoint sp179;
Create table subt_tab_distby_ao179 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao178 select * from subtransaction_temp;
Release Savepoint sp179;
Savepoint sp180;
Create table subt_tab_distby_ao180 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao179 select * from subtransaction_temp;
Release Savepoint sp180;
Rollback to sp132;
Savepoint sp182;
Create table subt_tab_distby_ao182 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao182 select * from subtransaction_temp;
Rollback to sp182;
Savepoint sp183;
Create table subt_tab_distby_ao183 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao183 select * from subtransaction_temp;
Rollback to sp183;
Savepoint sp184;
Create table subt_tab_distby_ao184 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao184 select * from subtransaction_temp;
Rollback to sp184;
Savepoint sp185;
Create table subt_tab_distby_ao185 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao185 select * from subtransaction_temp;
Rollback to sp185;
Savepoint sp186;
Create table subt_tab_distby_ao186 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao186 select * from subtransaction_temp;
Rollback to sp186;
Savepoint sp187;
Create table subt_tab_distby_ao187 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao187 select * from subtransaction_temp;
Rollback to sp187;
Savepoint sp188;
Create table subt_tab_distby_ao188 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao188 select * from subtransaction_temp;
Rollback to sp188;
Savepoint sp189;
Create table subt_tab_distby_ao189 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao189 select * from subtransaction_temp;
Rollback to sp189;
Savepoint sp190;
Create table subt_tab_distby_ao190 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao190 select * from subtransaction_temp;
Rollback to sp190;
Savepoint sp191;
Create table subt_tab_distby_ao191 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao191 select * from subtransaction_temp;
Rollback to sp191;
Savepoint sp192;
Create table subt_tab_distby_ao192 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao192 select * from subtransaction_temp;
Rollback to sp192;
Savepoint sp193;
Create table subt_tab_distby_ao193 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao193 select * from subtransaction_temp;
Rollback to sp193;
Savepoint sp194;
Create table subt_tab_distby_ao194 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao194 select * from subtransaction_temp;
Rollback to sp194;
Savepoint sp195;
Create table subt_tab_distby_ao195 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao195 select * from subtransaction_temp;
Rollback to sp195;
Savepoint sp196;
Create table subt_tab_distby_ao196 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao196 select * from subtransaction_temp;
Rollback to sp196;
Savepoint sp197;
Create table subt_tab_distby_ao197 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao197 select * from subtransaction_temp;
Rollback to sp197;
Savepoint sp198;
Create table subt_tab_distby_ao198 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao198 select * from subtransaction_temp;
Rollback to sp198;
Savepoint sp199;
Create table subt_tab_distby_ao199 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao199 select * from subtransaction_temp;
Rollback to sp199;
Savepoint sp200;
Create table subt_tab_distby_ao200 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao200 select * from subtransaction_temp;
Rollback to sp200;
Savepoint sp201;
Create table subt_tab_distby_ao201 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao201 select * from subtransaction_temp;
Rollback to sp201;
Release Savepoint sp112;
COMMIT;

SELECT CURRENT_TIMESTAMP;

