/*-------------------------------------------------------------------------
 *
 * pg_language.h
 *	  definition of the system "language" relation (pg_language)
 *	  along with the relation's initial contents.
 *
 *
 * Portions Copyright (c) 1996-2008, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * $PostgreSQL: pgsql/src/include/catalog/pg_language.h,v 1.32 2008/01/01 19:45:56 momjian Exp $
 *
 * NOTES
 *	  the genbki.sh script reads this file and generates .bki
 *	  information from the DATA() statements.
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_LANGUAGE_H
#define PG_LANGUAGE_H

#include "catalog/genbki.h"

/* TIDYCAT_BEGINDEF

   CREATE TABLE pg_language
   with (relid=2612)
   ( 
   lanname        name, 
   lanowner       oid, 
   lanispl        boolean, -- Is a procedural language
   lanpltrusted   boolean, -- PL is trusted
   lanplcallfoid  oid,     -- Call handler for PL
   laninline      oid,     -- Optional anonymous-block handler function
   lanvalidator   oid,     -- optional validation function
   lanacl         aclitem[] -- Access privileges
   );

   create unique index on pg_language(lanname) with (indexid=2681, CamelCase=LanguageName, syscacheid=LANGNAME, syscache_nbuckets=4);
   create unique index on pg_language(oid) with (indexid=2682, CamelCase=LanguageOid, syscacheid=LANGOID, syscache_nbuckets=4);

   alter table pg_language add fk lanplcallfoid on pg_proc(oid);
   alter table pg_language add fk lanvalidator on pg_proc(oid);
   alter table pg_language add fk lanowner on pg_authid(oid);

   TIDYCAT_ENDDEF
*/
/* TIDYCAT_BEGIN_CODEGEN 

   WARNING: DO NOT MODIFY THE FOLLOWING SECTION: 
   Generated by tidycat.pl version 27.
   on Tue Jun  7 15:41:32 2011
*/


/*
 TidyCat Comments for pg_language:
  Table has an Oid column.
  Table does not have static type (only legal for pre-3.3 tables). 

*/

/* ----------------
 *		pg_language definition.  cpp turns this into
 *		typedef struct FormData_pg_language
 * ----------------
 */
#define LanguageRelationId	2612

CATALOG(pg_language,2612)
{
	NameData	lanname;		/* Language name */
	Oid			lanowner;		/* Language's owner */
	bool		lanispl;		/* Is a procedural language */
	bool		lanpltrusted;	/* PL is trusted */
	Oid			lanplcallfoid;	/* Call handler for PL */
	Oid			laninline;		/* Optional anonymous-block handler function */
	Oid			lanvalidator;	/* optional validation function */
	aclitem		lanacl[1];		/* Access privileges */
} FormData_pg_language;


/* ----------------
 *		Form_pg_language corresponds to a pointer to a tuple with
 *		the format of pg_language relation.
 * ----------------
 */
typedef FormData_pg_language *Form_pg_language;


/* ----------------
 *		compiler constants for pg_language
 * ----------------
 */
#define Natts_pg_language				8
#define Anum_pg_language_lanname		1
#define Anum_pg_language_lanowner		2
#define Anum_pg_language_lanispl		3
#define Anum_pg_language_lanpltrusted	4
#define Anum_pg_language_lanplcallfoid	5
#define Anum_pg_language_laninline		6
#define Anum_pg_language_lanvalidator	7
#define Anum_pg_language_lanacl			8


/* TIDYCAT_END_CODEGEN */


/* ----------------
 *		initial contents of pg_language
 * ----------------
 */

DATA(insert OID = 12 ( "internal" PGUID f f 0 0 2246 _null_ ));
DESCR("built-in functions");
#define INTERNALlanguageId 12
DATA(insert OID = 13 ( "c" PGUID f f 0 0 2247 _null_ ));
DESCR("dynamically-loaded C functions");
#define ClanguageId 13
DATA(insert OID = 14 ( "sql" PGUID f t 0 0 2248 _null_ ));
DESCR("SQL-language functions");
#define SQLlanguageId 14

#endif   /* PG_LANGUAGE_H */
