/*-------------------------------------------------------------------------
 *
 * pg_tidycat.h
 *	  
 * Copyright (c) 2011 Greenplum inc.
 *
 * WARNING: DO NOT MODIFY THIS FILE: 
 *  Generated by ./tidycat.pl version 31
 *  on Thu Sep  1 16:43:17 2011
 *-------------------------------------------------------------------------
 */


#include "catalog/pg_attribute_encoding.h"
#include "catalog/pg_auth_time_constraint.h"
#include "catalog/pg_compression.h"
#include "catalog/pg_proc_callback.h"
#include "catalog/pg_partition_encoding.h"
#include "catalog/pg_type_encoding.h"
