#
# Makefile for optimizer
#
# src/backend/gporca/libnaucrates/Makefile
#

subdir = src/backend/gporca/libnaucrates
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = src

include $(top_srcdir)/src/backend/common.mk
