#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/resource_manager
#
# IDENTIFICATION
#    src/backend/utils/resource_manager/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/resource_manager
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = resource_manager.o memquota.o

include $(top_srcdir)/src/backend/common.mk
