r301 '/', '/7-0/common/gpdb-features.html'
r301 '/index.html', '/7-0/common/gpdb-features.html'
r301 '/7-0/index.html', '/7-0/common/gpdb-features.html'
r301 %r{(.*)/homenav.html}, '/7-0/common/gpdb-features.html'
r301 '/pxf/5-13/installing_pxf.html', 'https://github.com/greenplum-db/pxf/blob/master/package/README.md'
