-- start_ignore
SET gp_create_table_random_default_distribution=off;
-- end_ignore
Begin;
CREATE TYPE compfoo_ag21 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag23 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag24 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag25 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag26 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag27 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag28 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag222 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag2222 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag233 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag2333 AS (f1 int, f2 text);
CREATE TYPE compfoo_ag23333 AS (f1 int, f2 text);
insert into r1 values (generate_series(1,1600));
create table ag1(a int);
CREATE TYPE compfoo_sc21 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc23 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc24 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc25 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc26 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc27 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc28 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc222 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc2222 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc233 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc2333 AS (f1 int, f2 text);
CREATE TYPE compfoo_sc23333 AS (f1 int, f2 text);
insert into r1 values (generate_series(1,1600));
insert into ao values (generate_series(1,100));