#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for gpopt
#
#-------------------------------------------------------------------------

subdir = src/backend/gpopt/relcache
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gpopt/gpopt.mk

OBJS = CMDProviderRelcache.o

include $(top_srcdir)/src/backend/common.mk
