#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/workfile_manager
#
# IDENTIFICATION
#    src/backend/utils/workfile_manager/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/workfile_manager
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = workfile_mgr.o workfile_diskspace.o workfile_file.o \
		workfile_segmentspace.o workfile_queryspace.o

include $(top_srcdir)/src/backend/common.mk
