-- start_ignore
SET gp_create_table_random_default_distribution=off;
-- end_ignore
drop table pg2_ao_table_bitmap_index_template;
drop table pg2_ao_table_btree_index_template;
drop table pg2_ao_table_for_alter_template;
drop table pg2_ao_table_gist_index_template;
drop table pg2_co_table_bitmap_index_template;
drop table pg2_co_table_btree_index_template;
drop table pg2_co_table_for_alter_template;
drop table pg2_co_table_gist_index_template;
drop table pg2_heap_table_bitmap_index_template;
drop table pg2_heap_table_btree_index_template;
drop table pg2_heap_table_unique_index_template;
drop table pg2_heap_table_for_alter_template;
drop table pg2_heap_table_gist_index_template;
drop tablespace pg2_dropts_template;
drop tablespace pg2_ao_ts1_template;
drop tablespace pg2_ao_ts2_template;
drop tablespace pg2_co_ts1_template;
drop tablespace pg2_co_ts2_template;
drop tablespace pg2_heap_ts1_template;
drop tablespace pg2_heap_ts2_template;
drop tablespace pg2_ts1_template;
