# Copyright (c) 2022-2023, PostgreSQL Global Development Group

backend_sources += files(
  'session_state.c',
)

install_data('errcodes.txt',
  install_dir: dir_data,
)

subdir('activity')
subdir('adt')
subdir('cache')
subdir('error')
subdir('fmgr')
subdir('hash')
subdir('init')
subdir('mb')
subdir('misc')
subdir('mmgr')
subdir('resowner')
subdir('sort')
subdir('time')
subdir('datumstream')
subdir('etcd_lib')
subdir('gdd')
subdir('resgroup')
subdir('resscheduler')
subdir('gp')
subdir('workfile_manager')
subdir('resource_manager')
subdir('hyperloglog')
