-- 
-- @created 2009-01-27 14:00:00
-- @modified 2013-06-24 17:00:00
-- @tags ddl schema_topology
-- @description This ddl comprises of create and alter group statements

\c db_test_bed
CREATE ROLE grp_role1;
CREATE ROLE grp_role2;
CREATE GROUP db_group1 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
CREATE GROUP db_grp2 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
CREATE GROUP db_grp3 WITH NOCREATEROLE NOCREATEUSER;
CREATE GROUP db_grp4 WITH CREATEROLE CREATEUSER;
CREATE GROUP db_grp5 WITH VALID UNTIL '2009-02-13 01:51:15';
CREATE GROUP db_grp6 WITH IN ROLE grp_role1; 
CREATE GROUP db_grp7 WITH IN GROUP db_group1; 
CREATE GROUP db_grp8 WITH ROLE grp_role2;
CREATE GROUP db_grp9 WITH ADMIN db_grp8;
CREATE GROUP db_grp10 WITH USER db_group1;
CREATE GROUP db_grp11 SYSID 100 ;
DROP RESOURCE QUEUE grp_rsq1;
CREATE RESOURCE QUEUE grp_rsq1 ACTIVE THRESHOLD 1;
CREATE GROUP db_grp12 RESOURCE QUEUE grp_rsq1;


CREATE USER test_user_1;
ALTER GROUP db_grp12 ADD USER test_user_1;
ALTER GROUP db_grp12 DROP USER test_user_1;
ALTER GROUP db_grp12 RENAME TO new_db_grp12;
ALTER GROUP new_db_grp12 RENAME TO db_grp12;
