-- 
-- @created 2009-01-27 14:00:00
-- @modified 2013-06-24 17:00:00
-- @tags ddl schema_topology

\c db_test_bed
--start_ignore
DROP ROLE dba_role1;
CREATE ROLE dba_role1 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';

--end_ignore

CREATE USER db_user1 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
CREATE USER db_user2 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
CREATE USER db_user3 WITH NOCREATEROLE NOCREATEUSER;
CREATE USER db_user4 WITH CREATEROLE CREATEUSER;
CREATE USER db_user5 WITH VALID UNTIL '2009-02-13 01:51:15';
CREATE USER db_user6 WITH IN ROLE dba_role1; 
CREATE GROUP db_user_grp1;
CREATE USER db_user7 WITH IN GROUP db_user_grp1; 
CREATE USER db_user8 WITH ROLE db_user7;
CREATE USER db_user9 WITH ADMIN db_user8;
CREATE USER db_user10 WITH USER db_user1;
CREATE USER db_user11 SYSID 100 ;
DROP RESOURCE QUEUE resqueu3;
CREATE RESOURCE QUEUE resqueu3 ACTIVE THRESHOLD 1;
CREATE USER db_user12 RESOURCE QUEUE resqueu3;


ALTER USER db_user1 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER USER db_user2 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
ALTER USER db_user3 WITH CREATEROLE CREATEUSER;
ALTER USER db_user4 WITH NOCREATEROLE NOCREATEUSER;
ALTER USER db_user5 WITH VALID UNTIL '2009-06-13 01:51:15';
ALTER USER db_user6 WITH CONNECTION LIMIT 5;
CREATE RESOURCE QUEUE resqueu4 ACTIVE THRESHOLD 1;
ALTER USER db_user7 WITH RESOURCE QUEUE resqueu4;
ALTER USER db_user8 RENAME TO new_user8; 
CREATE SCHEMA db_schema2;
ALTER USER db_user9 SET search_path TO db_schema2;
ALTER USER db_user9 RESET search_path ;
