
BLD_TOP := ../..
include $(BLD_TOP)/make/gpo.mk

INCDIRS=-I $(LIBGPOS)/include -I $(BLD_TOP)/libnaucrates/include -I $(BLD_TOP)/libgpopt/include
SUBDIRS = base metadata mdcache minidump operators optimizer search translate xforms engine cost eval

all: objs

