#############
# RESOURCES #
#############
resources:
- name: gpos_github_release
  type: github-release
  source:
    user: greenplum-db
    repository: gpos
    access_token: {{gposbot_access_token}}
- name: orca_github_release
  type: github-release
  source:
    user: greenplum-db
    repository: gporca
    access_token: {{gporcabot_access_token}}
- name: gpos_src
  type: git
  source:
    branch: master
    private_key: {{gpos_deploy_key}}
    uri: git@github.com:greenplum-db/gpos.git
- name: gpdb_src
  type: git
  source:
    branch: master
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:greenplum-db/gpdb.git
- name: xerces_patch
  type: git
  source:
    branch: master
    paths:
    - patches/xerces-c-gpdb.patch
    - concourse/xerces-c
    - concourse/package_tarball.bash
    private_key: {{gporca_deploy_key}}
    uri: git@github.com:greenplum-db/gporca.git
- name: orca_src
  type: git
  source:
    branch: master
    private_key: {{gporca_deploy_key}}
    uri: git@github.com:greenplum-db/gporca.git
- name: bin_xerces
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_xerces_centos5.tar.gz
- name: bin_gpos_debug
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_centos5_debug.tar.gz
- name: bin_gpos_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_centos5_release.tar.gz
- name: bin_orca_debug
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_centos5_debug.tar.gz
- name: bin_orca_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_centos5_release.tar.gz
- name: regression_diffs
  type: s3
  source:
     access_key_id: {{aws-access-key-id}}
     bucket: {{bucket-name}}
     region_name: {{aws-region}}
     secret_access_key: {{aws-secret-access-key}}
     versioned_file: regression.diffs
- name: regression_out
  type: s3
  source:
     access_key_id: {{aws-access-key-id}}
     bucket: {{bucket-name}}
     region_name: {{aws-region}}
     secret_access_key: {{aws-secret-access-key}}
     versioned_file: regression.out

########
# JOBS #
########
jobs:
- name: gpos_publish_tag
  max_in_flight: 1
  plan:
  - aggregate:
    - get: gpos_src
      passed:
      - gpos_release
      - gpos_debug
      trigger: true
    - get: bin_gpos_release
      passed:
      - gpos_release
    - get: bin_gpos_debug
      passed:
      - gpos_debug
  - task: gpos_publish_tag
    file: gpos_src/concourse/publish_tag.yml
  - put: gpos_github_release
    params:
      name: gpos_github_release_stage/tag.txt
      tag: gpos_github_release_stage/tag.txt
      commitish: gpos_github_release_stage/commit.txt
      globs:
        - gpos_github_release_stage/bin_gpos_centos5_release.tar.gz
        - gpos_github_release_stage/bin_gpos_centos5_debug.tar.gz

- name: orca_publish_tag
  max_in_flight: 1
  plan:
  - aggregate:
    - get: orca_src
      trigger: true
      passed:
      - orca_release
      - orca_debug
    - get: bin_orca_release
      passed:
      - orca_release
    - get: bin_orca_debug
      passed:
      - orca_debug
  - task: orca_publish_tag
    file: orca_src/concourse/publish_tag.yml
  - put: orca_github_release
    params:
      name: orca_github_release_stage/tag.txt
      tag: orca_github_release_stage/tag.txt
      commitish: orca_github_release_stage/commit.txt
      globs:
        - orca_github_release_stage/bin_orca_centos5_release.tar.gz

- name: gp_xerces
  max_in_flight: 2
  plan:
  - get: xerces_patch
    trigger: true
  - aggregate:
    - task: build
      file: xerces_patch/concourse/xerces-c/build_xerces_centos5.yml
  - aggregate:
    - task: package_tarball
      file: xerces_patch/concourse/xerces-c/package_tarball_centos5.yml
  - aggregate:
    - put: bin_xerces
      params:
        from: package_tarball_centos5/bin_xerces_centos5.tar.gz

- name: gpos_release
  max_in_flight: 2
  plan:
  - get: gpos_src
    trigger: true
  - task: build_and_test_release
    file: gpos_src/concourse/build_centos5_release.yml
  - task: package_tarball_release
    file: gpos_src/concourse/package_tarball_centos5_release.yml
  - put: bin_gpos_release
    params:
      from: package_tarball_release/bin_gpos_release.tar.gz

- name: gpos_debug
  max_in_flight: 2
  plan:
  - get: gpos_src
    trigger: true
  - task: build_and_test_debug
    file: gpos_src/concourse/build_centos5_debug.yml
  - task: package_tarball_debug
    file: gpos_src/concourse/package_tarball_centos5_debug.yml
  - put: bin_gpos_debug
    params:
      from: package_tarball_debug/bin_gpos_debug.tar.gz

- name: orca_release
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_gpos_release
    passed:
    - gpos_publish_tag
    trigger: true
  - get: bin_xerces
    passed:
    - gp_xerces
    trigger: true
  - task: build_and_test_release
    file: orca_src/concourse/build_and_test_centos5_release.yml
  - task: package_tarball_release
    file: orca_src/concourse/package_tarball_centos5_release.yml
  - put: bin_orca_release
    params:
      from: package_tarball_release/bin_orca_release.tar.gz

- name: orca_debug
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_gpos_debug
    passed:
    - gpos_publish_tag
    trigger: true
  - get: bin_xerces
    passed:
    - gp_xerces
    trigger: true
  - task: build_and_test_debug
    file: orca_src/concourse/build_and_test_centos5_debug.yml
  - task: package_tarball_debug
    file: orca_src/concourse/package_tarball_centos5_debug.yml
  - put: bin_orca_debug
    params:
      from: package_tarball_debug/bin_orca_debug.tar.gz
