#
# Makefile for optimizer
#
# src/backend/gporca/libnaucrates/src/xml/Makefile
#

subdir = src/backend/gporca/libnaucrates/src/xml
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS        = CDXLMemoryManager.o \
              CDXLSections.o \
              CXMLSerializer.o \
              dxltokens.o

include $(top_srcdir)/src/backend/common.mk

