#
# Makefile for optimizer
#
# src/backend/gporca/libgpos/src/test/Makefile
#

subdir = src/backend/gporca/libgpos/src/memory
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

include $(top_srcdir)/src/backend/common.mk


