.PHONY: gpnetbench
all: gpnetbench

gpnetbench:
	$(MAKE) -C gpnetbench all

clean:
	$(MAKE) -C gpnetbench clean

distclean:
	$(MAKE) -C gpnetbench distclean

install: all
	$(MAKE) -C gpnetbench install
