#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mdver
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/utils/mdver/Makefile,v 1.15 2015/11/11 17:45:09 
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/mdver
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = mdver_global_generation.o mdver_local_generation.o mdver_utils.o \
       mdver_inv_translator.o

include $(top_srcdir)/src/backend/common.mk
