TINCHOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export TINCHOME=$TINCHOME
TINCREPOHOME=$TINCHOME/tincrepo
export TINCREPOHOME=$TINCREPOHOME

export PYTHONPATH=$TINCHOME:$TINCHOME/ext:$PYTHONPATH:$TINCREPOHOME
export PATH=$TINCHOME:$TINCHOME/ext:$TINCHOME/ext/unittest2:$TINCHOME/sbin/:$PATH
