DROP TABLE IF EXISTS nation;
DROP TABLE IF EXISTS region;
DROP TABLE IF EXISTS part;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS partsupp;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS lineitem;

set default_table_access_method=ao_column;


CREATE TABLE nation (
    N_NATIONKEY  INTEGER NOT NULL,
    N_NAME       TEXT NOT NULL,
    N_REGIONKEY  INTEGER NOT NULL,
    N_COMMENT    VARCHAR(152));

\copy nation FROM 'data/tpch/nation.csv'  DELIMITER ',' CSV;


CREATE TABLE region (
    R_REGIONKEY  INTEGER NOT NULL,
    R_NAME       TEXT NOT NULL,
    R_COMMENT    VARCHAR(152));

\copy region FROM 'data/tpch/region.csv'  DELIMITER ',' CSV;


CREATE TABLE part (
    P_PARTKEY     INTEGER NOT NULL,
    P_NAME        VARCHAR(55) NOT NULL,
    P_MFGR        TEXT NOT NULL,
    P_BRAND       TEXT NOT NULL,
    P_TYPE        VARCHAR(25) NOT NULL,
    P_SIZE        INTEGER NOT NULL,
    P_CONTAINER   TEXT NOT NULL,
    P_RETAILPRICE DECIMAL(15,2) NOT NULL,
    P_COMMENT     VARCHAR(23) NOT NULL);

\copy part FROM 'data/tpch/part.csv'  DELIMITER ',' CSV;


CREATE TABLE supplier (
    S_SUPPKEY     INTEGER NOT NULL,
    S_NAME        TEXT NOT NULL,
    S_ADDRESS     VARCHAR(40) NOT NULL,
    S_NATIONKEY   INTEGER NOT NULL,
    S_PHONE       TEXT NOT NULL,
    S_ACCTBAL     DECIMAL(15,2) NOT NULL,
    S_COMMENT     VARCHAR(101) NOT NULL);

\copy supplier FROM 'data/tpch/supplier.csv'  DELIMITER ',' CSV;


CREATE TABLE partsupp (
    PS_PARTKEY     INTEGER NOT NULL,
    PS_SUPPKEY     INTEGER NOT NULL,
    PS_AVAILQTY    INTEGER NOT NULL,
    PS_SUPPLYCOST  DECIMAL(15,2)  NOT NULL,
    PS_COMMENT     VARCHAR(199) NOT NULL );

\copy partsupp FROM 'data/tpch/partsupp.csv'  DELIMITER ',' CSV;


CREATE TABLE customer (
    C_CUSTKEY     INTEGER NOT NULL,
    C_NAME        VARCHAR(25) NOT NULL,
    C_ADDRESS     VARCHAR(40) NOT NULL,
    C_NATIONKEY   INTEGER NOT NULL,
    C_PHONE       TEXT NOT NULL,
    C_ACCTBAL     DECIMAL(15,2)   NOT NULL,
    C_MKTSEGMENT  TEXT NOT NULL,
    C_COMMENT     VARCHAR(117) NOT NULL);

\copy customer FROM 'data/tpch/customer.csv'  DELIMITER ',' CSV;


CREATE TABLE orders (
    O_ORDERKEY       INT8 NOT NULL,
    O_CUSTKEY        INTEGER NOT NULL,
    O_ORDERSTATUS    TEXT NOT NULL,
    O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
    O_ORDERDATE      DATE NOT NULL,
    O_ORDERPRIORITY  TEXT NOT NULL,
    O_CLERK          TEXT NOT NULL,
    O_SHIPPRIORITY   INTEGER NOT NULL,
    O_COMMENT        VARCHAR(79) NOT NULL);

\copy orders FROM 'data/tpch/orders.csv'  DELIMITER ',' CSV;

CREATE TABLE lineitem (
    L_ORDERKEY    INT8 NOT NULL,
    L_PARTKEY     INTEGER NOT NULL,
    L_SUPPKEY     INTEGER NOT NULL,
    L_LINENUMBER  INTEGER NOT NULL,
    L_QUANTITY    DECIMAL(15,2) NOT NULL,
    L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
    L_DISCOUNT    DECIMAL(15,2) NOT NULL,
    L_TAX         DECIMAL(15,2) NOT NULL,
    L_RETURNFLAG  TEXT NOT NULL,
    L_LINESTATUS  TEXT NOT NULL,
    L_SHIPDATE    DATE NOT NULL,
    L_COMMITDATE  DATE NOT NULL,
    L_RECEIPTDATE DATE NOT NULL,
    L_SHIPINSTRUCT TEXT NOT NULL,
    L_SHIPMODE     TEXT NOT NULL,
    L_COMMENT      VARCHAR(44) NOT NULL);


\copy lineitem FROM 'data/tpch/lineitem.csv'  DELIMITER ',' CSV;
