subdir=src/backend/utils/fmgr
top_builddir=../../../../..
include $(top_builddir)/src/Makefile.global

TARGETS=dfmgr

dfmgr_MOCK_OBJS=\
	$(top_srcdir)/src/backend/utils/error/elog.o

include $(top_builddir)/src/backend/mock.mk
