subdir=src/backend/utils/fmgr
top_builddir=../../../../..
include $(top_builddir)/src/Makefile.global

TARGETS=dfmgr

include $(top_srcdir)/src/backend/mock.mk

dfmgr.t: $(MOCK_DIR)/backend/utils/error/elog_mock.o
