# Original Authors: Navneet Potti, Nabarun Nag and Jignesh Patel

# IP Address for the private VM network
ip_address = "192.168.10.200"

# Basic Vagrant config (API version 2)
Vagrant.configure(2) do |config|

  # Base box: Centos-7 box
  # NOTE: Over time the VMI below may become outdated, so may need to be
  #       substituted with a more recent VMI
  config.vm.box = "boxcutter/centos72"

  # Make this VM reachable on the host network as well, so that other
  # VM's running other browsers can access our dev server.
  config.vm.network :private_network, ip: ip_address

  # Give a reasonable amount of cpu and memory to the VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "gpdb-dev-host" # Name in VirtualBox
    vb.memory = 4096
    vb.cpus = 2
  end

  # Make the GPDB code folder will be visible as /gpdb in the virtual machine
  config.vm.synced_folder "../../.", "/gpdb"

  # Install packages that are needed to build and run GPDB
  config.vm.provision "shell", path: "vagrant-setup.sh"
  config.vm.provision "shell", path: "vagrant-build.sh"
  config.vm.provision "shell", path: "vagrant-configure-os.sh", args: ip_address
  config.vm.provision "shell", path: "vagrant-install.sh"

end
