-- start_ignore
SET gp_create_table_random_default_distribution=off;
-- end_ignore
-- Create User, Alter User

CREATE USER sync2_xuser1 WITH CREATEROLE CREATEUSER;
CREATE USER sync2_xuser2 WITH CREATEROLE CREATEUSER;

-- Alter User
ALTER USER sync1_xuser5 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER USER ck_sync1_xuser4 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER USER ct_xuser3 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER USER resync_xuser2 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER USER sync2_xuser1 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
