CREATE RESOURCE QUEUE db_resque100 ACTIVE THRESHOLD 2 COST THRESHOLD 2000.00;
CREATE RESOURCE QUEUE db_resque2 COST THRESHOLD 3000.00 OVERCOMMIT;
CREATE RESOURCE QUEUE DB_RESque3 COST THRESHOLD 2000.0 NOOVERCOMMIT;
CREATE RESOURCE QUEUE DB_RESQUE4 ACTIVE THRESHOLD 2  IGNORE THRESHOLD  1000.0;
CREATE RESOURCE QUEUE db_resque5 ACTIVE THRESHOLD 2 COST THRESHOLD 2000.00;
CREATE RESOURCE QUEUE db_resque6 COST THRESHOLD 3000.00 OVERCOMMIT;
CREATE RESOURCE QUEUE db_resque7 ACTIVE THRESHOLD 2 COST THRESHOLD 2000.00;

ALTER RESOURCE QUEUE db_resque100 ACTIVE THRESHOLD 3 COST THRESHOLD 1000.00;
ALTER RESOURCE QUEUE db_resque2 COST THRESHOLD 300.00 NOOVERCOMMIT;
ALTER RESOURCE QUEUE DB_RESque3 COST THRESHOLD 200.0 ;
ALTER RESOURCE QUEUE DB_RESQUE4 IGNORE THRESHOLD  500.0;
ALTER RESOURCE QUEUE db_resque5 OVERCOMMIT;
ALTER RESOURCE QUEUE db_resque6 NOOVERCOMMIT;
ALTER RESOURCE QUEUE db_resque7 ACTIVE THRESHOLD 5;

drop RESOURCE QUEUE db_resque100;
drop RESOURCE QUEUE db_resque2;
drop RESOURCE QUEUE db_resque3;
drop RESOURCE QUEUE db_resque4;
drop RESOURCE QUEUE db_resque5;
drop RESOURCE QUEUE db_resque6;
drop RESOURCE QUEUE db_resque7;

