CREATE ROLE mdt_db_role1 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
CREATE ROLE mdt_db_role2 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
CREATE ROLE mdt_db_role3 WITH NOCREATEROLE NOCREATEUSER;
CREATE ROLE mdt_db_role4 WITH CREATEROLE CREATEUSER;
CREATE ROLE mdt_db_role5 WITH VALID UNTIL '2009-02-13 01:51:15';
CREATE ROLE mdt_db_role6 WITH IN ROLE mdt_db_role1;
CREATE GROUP mdt_db_grp1;
CREATE ROLE mdt_db_role7 WITH IN GROUP mdt_db_grp1;
CREATE ROLE mdt_db_role8 WITH ROLE mdt_db_role7;
CREATE ROLE mdt_db_role9 WITH ADMIN mdt_db_role8;
CREATE ROLE mdt_db_role10 WITH USER mdt_db_role1;
CREATE ROLE mdt_db_role11 SYSID 100 ;
CREATE RESOURCE QUEUE mdt_db_resque1 ACTIVE THRESHOLD 2 COST THRESHOLD 2000.00;
CREATE ROLE  mdt_db_role12 RESOURCE QUEUE mdt_db_resque1;
CREATE role mdt_db_role13 ;
CREATE role mdt_db_role14;
CREATE role mdt_db_role15;
CREATE role mdt_db_role16;
CREATE role mdt_db_role17;
CREATE role mdt_db_role18 login;
CREATE role mdt_db_role19 login ENCRYPTED PASSWORD 'passwd';
CREATE role mdt_db_role20;
CREATE role mdt_db_role21;
CREATE role mdt_db_role22;
CREATE role mdt_db_role23;
CREATE role mdt_db_role24;
CREATE role mdt_db_role25;
CREATE role mdt_db_role26;
CREATE role mdt_db_role27;

ALTER ROLE mdt_db_role1 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER ROLE mdt_db_role2 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
ALTER ROLE mdt_db_role3 WITH CREATEROLE CREATEUSER;
ALTER ROLE mdt_db_role4 WITH NOCREATEROLE NOCREATEUSER;
ALTER ROLE mdt_db_role5 WITH VALID UNTIL '2009-06-13 01:51:15';
ALTER ROLE mdt_db_role6 WITH CONNECTION LIMIT 5;
ALTER ROLE mdt_db_role7 WITH RESOURCE QUEUE mdt_db_resque1;
ALTER ROLE mdt_db_role8 RENAME TO mdt_new_role8;
CREATE SCHEMA mdt_db_schema1;
ALTER ROLE mdt_db_role9 SET search_path TO mdt_db_schema1;
ALTER ROLE mdt_db_role10 SET search_path TO mdt_db_schema1;
ALTER ROLE mdt_db_role10 RESET search_path ;
ALTER role mdt_db_role13 WITH SUPERUSER;
ALTER role mdt_db_role14 WITH CREATEDB;
ALTER role mdt_db_role15 WITH INHERIT;
ALTER role mdt_db_role16 WITH LOGIN;
ALTER role mdt_db_role17 WITH CONNECTION LIMIT  1;
ALTER role mdt_db_role18 WITH ENCRYPTED PASSWORD 'passwd';;
ALTER role mdt_db_role19 WITH UNENCRYPTED PASSWORD 'passwd';
ALTER role mdt_db_role20 WITH NOSUPERUSER;
ALTER role mdt_db_role21 WITH NOCREATEDB;
ALTER role mdt_db_role22 WITH NOINHERIT;
ALTER role mdt_db_role23 WITH NOLOGIN;
ALTER role mdt_db_role24 WITH CREATEROLE;
ALTER role mdt_db_role25 WITH NOCREATEROLE;
ALTER role mdt_db_role26 WITH CREATEUSER;
ALTER role mdt_db_role27 WITH NOCREATEUSER;

drop role mdt_db_grp1 ;
drop role mdt_db_role1 ;
drop role mdt_db_role2 ;
drop role mdt_db_role3 ;
drop role mdt_db_role4 ;
drop role mdt_db_role5 ;
drop role mdt_db_role6 ;
drop role mdt_db_role7 ;
drop role mdt_new_role8 ;
drop role mdt_db_role9 ;
drop role mdt_db_role10 ;
drop role mdt_db_role11 ;
drop role mdt_db_role12 ;
drop schema mdt_db_schema1;
drop resource queue mdt_db_resque1;
drop role mdt_db_role13 ;
drop role mdt_db_role14;
drop role mdt_db_role15;
drop role mdt_db_role16;
drop role mdt_db_role17;
drop role mdt_db_role18;
drop role mdt_db_role19;
drop role mdt_db_role20;
drop role mdt_db_role21;
drop role mdt_db_role22;
drop role mdt_db_role23;
drop role mdt_db_role24;
drop role mdt_db_role25;
drop role mdt_db_role26;
drop role mdt_db_role27;

