CREATE USER mdt_db_user1 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
CREATE USER mdt_db_user2 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
CREATE USER mdt_db_user3 WITH NOCREATEROLE NOCREATEUSER;
CREATE USER mdt_db_user4 WITH CREATEROLE CREATEUSER;
CREATE USER mdt_db_user5 WITH VALID UNTIL '2009-02-13 01:51:15';
CREATE ROLE mdt_db_role1;
CREATE USER mdt_db_user6 WITH IN ROLE mdt_db_role1; 
CREATE GROUP mdt_db_user_grp1;
CREATE USER mdt_db_user7 WITH IN GROUP mdt_db_user_grp1; 
CREATE USER mdt_db_user8 WITH ROLE mdt_db_user7;
CREATE USER mdt_db_user9 WITH ADMIN mdt_db_user8;
CREATE USER mdt_db_user10 WITH USER mdt_db_user1;
CREATE USER mdt_db_user11 SYSID 100 ;
CREATE RESOURCE QUEUE mdt_resqueu3 ACTIVE THRESHOLD 1;
CREATE USER mdt_db_user12 RESOURCE QUEUE mdt_resqueu3;
CREATE USER mdt_db_user13;
CREATE USER mdt_db_user14;
CREATE USER mdt_db_user15;
CREATE USER mdt_db_user16;
CREATE USER mdt_db_user17;
CREATE USER mdt_db_user18 login;
CREATE USER mdt_db_user19 login ENCRYPTED PASSWORD 'passwd';
CREATE USER mdt_db_user20;
CREATE USER mdt_db_user21;
CREATE USER mdt_db_user22;
CREATE USER mdt_db_user23;
CREATE USER mdt_db_user24;
CREATE USER mdt_db_user25;
CREATE USER mdt_db_user26;
CREATE USER mdt_db_user27;

ALTER USER mdt_db_user1 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
ALTER USER mdt_db_user2 WITH SUPERUSER CREATEDB  INHERIT LOGIN CONNECTION LIMIT  1 ENCRYPTED PASSWORD 'passwd';
ALTER USER mdt_db_user3 WITH CREATEROLE CREATEUSER;
ALTER USER mdt_db_user4 WITH NOCREATEROLE NOCREATEUSER;
ALTER USER mdt_db_user5 WITH VALID UNTIL '2009-06-13 01:51:15';
ALTER USER mdt_db_user6 WITH CONNECTION LIMIT 5;
CREATE RESOURCE QUEUE mdt_resqueu4 ACTIVE THRESHOLD 1;
ALTER USER mdt_db_user7 WITH RESOURCE QUEUE mdt_resqueu4;
ALTER USER mdt_db_user8 RENAME TO mdt_new_user8; 
CREATE SCHEMA mdt_db_schema2;
ALTER USER mdt_db_user9 SET search_path TO mdt_db_schema2;
ALTER USER mdt_db_user10 SET search_path TO mdt_db_schema2;
ALTER USER mdt_db_user10 RESET search_path ;
ALTER USER mdt_db_user13 WITH SUPERUSER;
ALTER USER mdt_db_user14 WITH CREATEDB;
ALTER USER mdt_db_user15 WITH INHERIT;
ALTER USER mdt_db_user16 WITH LOGIN;
ALTER USER mdt_db_user17 WITH CONNECTION LIMIT  1;
ALTER USER mdt_db_user18 WITH ENCRYPTED PASSWORD 'passwd';
ALTER USER mdt_db_user19 WITH UNENCRYPTED PASSWORD 'passwd';
ALTER USER mdt_db_user20 WITH NOSUPERUSER;
ALTER USER mdt_db_user21 WITH NOCREATEDB;
ALTER USER mdt_db_user22 WITH NOINHERIT;
ALTER USER mdt_db_user23 WITH NOLOGIN;
ALTER USER mdt_db_user24 WITH CREATEROLE;
ALTER USER mdt_db_user25 WITH NOCREATEROLE;
ALTER USER mdt_db_user26 WITH CREATEUSER;
ALTER USER mdt_db_user27 WITH NOCREATEUSER;

drop user mdt_db_user1;
drop user mdt_db_user2;
drop user mdt_db_user3;
drop user mdt_db_user4;
drop user mdt_db_user5;
drop user mdt_db_user6;
drop user mdt_db_user7;
drop user mdt_new_user8;
drop user mdt_db_user9;
drop user mdt_db_user10;
drop user mdt_db_user11;
drop user mdt_db_user12;
drop group mdt_db_user_grp1;
drop resource queue mdt_resqueu3;
drop resource queue mdt_resqueu4;
drop schema mdt_db_schema2;
drop role mdt_db_role1;
drop USER mdt_db_user13 ;
drop USER mdt_db_user14;
drop USER mdt_db_user15;
drop USER mdt_db_user16;
drop USER mdt_db_user17;
drop USER mdt_db_user18;
drop USER mdt_db_user19;
drop USER mdt_db_user20;
drop USER mdt_db_user21;
drop USER mdt_db_user22;
drop USER mdt_db_user23;
drop USER mdt_db_user24;
drop USER mdt_db_user25;
drop USER mdt_db_user26;
drop USER mdt_db_user27;

