CREATE TABLE SUBSELECT_TBL1 (
  f1 integer,
  f2 integer,
  f3 float
);
		
INSERT INTO SUBSELECT_TBL1 VALUES (1, 2, 3); 
INSERT INTO SUBSELECT_TBL1 VALUES (2, 3, 4); 
INSERT INTO SUBSELECT_TBL1 VALUES (3, 4, 5); 
INSERT INTO SUBSELECT_TBL1 VALUES (1, 1, 1); 
INSERT INTO SUBSELECT_TBL1 VALUES (2, 2, 2); 
INSERT INTO SUBSELECT_TBL1 VALUES (3, 3, 3); 
INSERT INTO SUBSELECT_TBL1 VALUES (6, 7, 8); 
INSERT INTO SUBSELECT_TBL1 VALUES (8, 9, NULL); 
SELECT '' AS eight, * FROM SUBSELECT_TBL1 ORDER BY 2,3,4;

SELECT '' AS two, f1 AS "Constant Select" FROM SUBSELECT_TBL1
  WHERE f1 IN (SELECT 1) ORDER BY 2;
