#
# Makefile for optimizer
#
# src/backend/gporca/libgpos/src/memory/Makefile
#

subdir = src/backend/gporca/libgpos/src/memory
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS        = CAutoMemoryPool.o \
              CCacheFactory.o \
              CMemoryPool.o \
              CMemoryPoolManager.o \
              CMemoryPoolTracker.o \
              CMemoryVisitorPrint.o

include $(top_srcdir)/src/backend/common.mk

