#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/hyperloglog
#
# IDENTIFICATION
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/hyperloglog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = gp_hyperloglog.o

include $(top_srcdir)/src/backend/common.mk
