-- start_ignore
SET gp_create_table_random_default_distribution=off;
-- end_ignore
-- Create User, Alter User

CREATE USER sync1_xuser1 WITH CREATEROLE CREATEUSER;
CREATE USER sync1_xuser2 WITH CREATEROLE CREATEUSER;
CREATE USER sync1_xuser3 WITH CREATEROLE CREATEUSER;
CREATE USER sync1_xuser4 WITH CREATEROLE CREATEUSER;
CREATE USER sync1_xuser5 WITH CREATEROLE CREATEUSER;
CREATE USER sync1_xuser6 WITH CREATEROLE CREATEUSER;

-- Alter User
ALTER USER sync1_xuser1 WITH NOSUPERUSER NOCREATEDB  NOINHERIT NOLOGIN  UNENCRYPTED PASSWORD 'passwd';
