#!/bin/sh

# src/tools/make_etags

command -v etags >/dev/null || \
	{ echo "'etags' program not found" 1>&2; exit 1; }

rm -f ./TAGS

find `pwd`/ -type f -name '*.[chyl]' -not -name "*_mock.c" -print |
	xargs etags --append -o TAGS
