#!/usr/bin/env bash

DIR_OF_THIS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

>"$DIR_OF_THIS_FILE/../../CMakeLists.txt" cat <<EOF
# This CMakeLists does not build GPDB. It is intended for consumption by the
# CLion IDE, which depends on CMakeLists for code intelligence.

cmake_minimum_required(VERSION 2.4)
project(gpdb)

include_directories(src/include src/test/unit/cmockery)

file(GLOB_RECURSE SOURCES src/backend/*.c src/include/*.h src/backend/*.cpp)
add_executable(gpdb \${SOURCES})
EOF
